name: NPM Publish to GitHub Package Registry

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - run: echo "@ldx:registry=https://npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

    - run: npm publish
